### ISSUE TITLE
Little Guy attempting to get on Little Horse causing crashes.

### ISSUE THREAD

**Issue by Ynaught** [JPeroutek/LittleGuys#1]
I put the horse inside a monster spawner and it crashed on spawning them. I have yet to try to place a horse into the world yet so IDK if the spawner is related or if the horse itself is just the issue. Will do further testing and report back in a reply.

First crash log when issue discovered:
https://mclo.gs/STxnutK

Crash log when trying to reload into the world only to crash-on-load:
https://mclo.gs/eAnxQfh

**Comment by Ynaught** [comment]
UPDATE:
Spawner unrelated. It has to do with when a little guy tries to get on a horse, will update title to reflect such.


Worth noting, I used a "red" little guy. Stating this incase the horse converting has any part to play in this as I have not tested it with a non-colored little guy.

**Comment by JPeroutek** [comment]
I was able to reproduce, working on a fix now

**Comment by JPeroutek** [comment]
@Ynaught Should be fixed in v0.1.6, let me know if it looks good on your side!

**Comment by Ynaught** [comment]
Seems good. Finished testing. Could have swore I remember seeing the horse changing color to match the rider when mounted in the video demo. I re-checked the demo video and I must have mis-remembered. Either way. Problem seems fixed. So I'll mark the issue as closed now. 😄
